### ISSUE TITLE
Connecting this client with a gstreamer webrtcbin endpoint

### ISSUE THREAD

**Issue by ggovindan** [livekit/client-sdk-rust#37]
Forgive me for this ignorant question.

I want to be able to connect to one of the livekit servers to receive a video stream. I came across this client-sdk implemented in Rust (Thanks a lot for this!). 

I have the websocket url for the livekit server and the token. 
I tried implementing a webrtc client using gstreamer `webrtcbin` element similar to the example here (https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/1.20/subprojects/gst-examples/webrtc/sendrecv/gst-rust/src/main.rs)but that fails in the signalling.

Will I have to implement or use one of the client-sdk to make the connection and then feed the RTP packets to the gstreamer pipeline?

**Comment by theomonnom** [comment]
Hey @ggovindan, 
You can access video frames and feed them to gstreamer-rs using the [on_frame](https://github.com/livekit/client-sdk-rust/blob/4411f88b685092dd095ae254cb4ed43d0901df26/examples/simple_room/src/video_renderer.rs#L100) callback from the VideoTracks.
You cannot use webrtcbin because LiveKit uses its own custom signaling protocol.
I'll be really interested in having a gstreamer example, I can help you if you make a PR

**Comment by ggovindan** [comment]
Thanks @theomonnom ! I will make a PR soon!

**Comment by spiegela** [comment]
@ggovindan did you have any success with this?  I'm also interested in gstreamer -> livekit.  Thanks!

**Comment by spiegela** [comment]
Ok. I mis-read -- I wanted to go the reverse and publish from gstreamer to livekit -- I'll poke around some more

**Comment by MathieuDuponchelle** [comment]
https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/merge_requests/1262 should solve this :)

**Comment by MathieuDuponchelle** [comment]
(for the gst -> livekit direction)
